version : "3.3"
services:
  neo4j:
    image: "neo4j:3.5.32-community"
    volumes:
      - /data/volumes/sp09999/neo4j-db/:/data
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=neo4j/ouiouioui
  notebooks:
    build: miniconda/
    volumes:
      - /data/volumes/sp09999/python/notebooks/:/python/notebooks/
      - /data/volumes/sp09999/python/data/:/python/data/
    ports:
      - 8888:8888
    links:
      - "neo4j:database"
    command: jupyter-lab --ip=0.0.0.0 --no-browser --allow-root --notebook-dir=/python/
  fill-db:
    build: miniconda/
    volumes:
      - /data/volumes/sp09999/python/notebooks/:/python/notebooks/
      - /data/volumes/sp09999/python/data/:/python/data/
    command: python scraping/merge_dump_into_neo4j.py
    links:
      - "neo4j:database"
