version : "3.3"
services:

  neo4j:
    image: "neo4j:4.4.6-community"
    volumes:
      - ${VOLUMES_PATH}/neo4j-db/:/data
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=neo4j/ouiouioui
      - dbms_allow__upgrade=true
      - dbms_default__database=graph.db

  notebooks:
    build: miniconda/
    volumes:
      - ${VOLUMES_PATH}/python/notebooks/:/python/notebooks/
      - ${VOLUMES_PATH}/python/data/:/python/data/
    ports:
      - 8888:8888
    links:
      - "neo4j:database"
    command: jupyter-lab --ip=0.0.0.0 --no-browser --allow-root --notebook-dir=/python/

  fill-db-from-dump:
    build: miniconda/
    volumes:
      - ${VOLUMES_PATH}/python/data/:/python/data/
    command: python scraping/merge_from_dump.py
    links:
      - "neo4j:database"

  fill-db-from-api:
    build: miniconda/
    volumes:
      - ${VOLUMES_PATH}/python/data/:/python/data/
    command: python scraping/merge_from_api.py
    links:
      - "neo4j:database"
    environment:
      - CLIENT_ID
      - CLIENT_SECRET

  counts:
    build: miniconda/
    command: python scraping/get_db_counts.py
    links:
      - "neo4j:database"

  tfidf:
    build: miniconda/
    command: python scraping/get_artist_tfidf.py
    links:
      - "neo4j:database"
    environment:
      - ARTIST

  search-name:
    build: miniconda/
    command: python scraping/search_artists_name.py
    links:
      - "neo4j:database"
    environment:
      - ARTIST
